# All my aliases
alias vim="nvim"
alias nv="nvim"
alias v="nvim"
alias px="proxychains"
alias nf="neofetch"
alias s="sway"
alias l="ls --color=auto"
alias dnd="killall dunst"
alias f="fd . | fzf --preview 'bat --style=numbers --color=always {} 2>/dev/null' | xargs -r nvim"
