#!/bin/bash

# Take in the type of entry as the first CLI parameter
IN_OR_OUT=$1

# Take in the project ID as the second CLI parameter
PROJECT_ID=$2

# Take in the description as the third CLI parameter
DESCRIPTION=$3

# I think everyone knows I work as a cyber security analyst
TASK="Cyber Security"

if [ "$1" = "in" ]; then
	# Start the timer
	clockify-cli in -i=0 -p $PROJECT_ID -d "$DESCRIPTION" --task "$TASK" > /dev/null && echo "Started timer"
fi

if [ "$1" = "out" ]; then
	# End the timer
	clockify-cli out -i=0 > /dev/null && echo "Stopped timer"
fi
