#!/bin/bash

# This script will use ffmpeg to record a video from the screen and audio from the microphone will be separated into a separate file.

# If the argument is "start" then the recording will start.
# If the argument is "stop" then the recording will stop.

if [ "$1" = "start" ]; then
	# Start recording
	dunstify "🔴 Recording Started"
	wf-recorder -c h264_vaapi -d /dev/dri/renderD128 --file ~/screenrecords/wf-$(date +%Y-%m-%d_%H-%M-%S).mp4

fi

if [ "$1" = "stop" ]; then
	# Stop recording
	dunstify "🔴 Recording Stopped"
	killall -2 wf-recorder
fi
