#!/bin/bash

# This script will use scrot/grim to take a screenshot of the current screen based on the current compositor
FILENAME=$(date +%F_%T)

grim -g "$(slurp)" - | wl-copy && wl-paste -t image/png > /home/neo/screenshots/$FILENAME.png
dunstify "📸 Captured screenshot"
exit 0
