#!/bin/bash

FILENAME=$(date +%F_%T)
FOLDER="$HOME/media/screenshots"
mkdir -p $FOLDER

if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
    if [ "$1" = "full" ]; then
        grim - | wl-copy && wl-paste -t image/png > "$FOLDER/$FILENAME.png"
    else
        grim -g "$(slurp)" - | wl-copy && wl-paste -t image/png > "$FOLDER/$FILENAME.png"
    fi
else
    if [ "$1" = "full" ]; then
        flameshot full -p "$FOLDER" -c
    else
        flameshot gui -p "$FOLDER" -c
    fi
fi

dunstify "📸 Captured screenshot"
