#!/bin/bash

# This script will run the command 'gammastep -O 3000' if gammastep isn't already running.
# If gammastep is already running, it will run 'killall gammastep'

if pgrep gammastep > /dev/null
then
		killall gammastep
else
		gammastep -O 3000 &
fi
