#!/bin/bash

# Launch Windows 
if [ "$1" = "start" ]; then
	sudo virsh start Win10 &&
		remote-viewer spice://localhost:5900 > /dev/null 2>&1 &
fi

if [ "$1" = "shutdown" ]; then
	sudo virsh shutdown Win10 &&
		killall remote-viewer
fi
