#!/bin/bash

# This script will run the command 'waybar' if gammastep isn't already running.
# If waybar is already running, it will run 'killall waybar'

if pgrep waybar > /dev/null
then
		killall waybar
else
		waybar &
fi
