#!/bin/bash

# This script is used to increase/decrease/mute volume using PulseAudio

# Usage: vol [up|down|mute]
if [ "$1" = "up" ]; then
	pactl set-sink-volume 0 +5%
elif [ "$1" = "down" ]; then
	pactl set-sink-volume 0 -5%
elif [ "$1" = "mute" ]; then
	pactl set-sink-mute 0 toggle
else
	echo "Usage: vol [up|down|mute]"
fi
